### ISSUE TITLE
Decomposing DDFacet cube into sub-band images

### ISSUE THREAD

**Issue by Kincaidr** [keflavich/FITS_tools#10]
Hi,

I want to use the fitstools option --unstack to decompose a cube image into constituent sub-band images.

![image](https://user-images.githubusercontent.com/53697426/115151104-bb584080-a06b-11eb-89ce-93c30ccbc3b3.png)

I am not sure on the syntax required for this. Where do i specify number of planes to split?

I have tried fitstools --unstack 10 NAXIS4 image_cube.fits .

But it says

![image](https://user-images.githubusercontent.com/53697426/115151393-f313b800-a06c-11eb-93ee-1208fdf9b93d.png)

Here are the cube details:
![image](https://user-images.githubusercontent.com/53697426/115151318-a6c87800-a06c-11eb-97c0-a93de7cfecad.png)

i want to split it into 10 individual images.

Many thanks for help!

**Comment by keflavich** [comment]
Your issue is not related to this package.
